name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      gitea:
        image: gitea/gitea:1.17.2
        options: --name gitea
        volumes:
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        env:
          SECRET_KEY: abracadabra
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release -warnAsError
      - name: Test
        run: |
          # set the user credentials.
          GITEA_USERNAME='jane.doe'
          GITEA_PASSWORD='password'
          GITEA_EMAIL="$GITEA_USERNAME@example.com"

          # create user in gitea.
          docker exec --user git gitea gitea admin user create \
            --admin \
            --email "$GITEA_EMAIL" \
            --username "$GITEA_USERNAME" \
            --password "$GITEA_PASSWORD"
          curl \
              -s \
              -u "$GITEA_USERNAME:$GITEA_PASSWORD" \
              -X 'PATCH' \
              -H 'Accept: application/json' \
              -H 'Content-Type: application/json' \
              -d "{\"full_name\": \"$GITEA_USERNAME\"}" \
              "http://localhost:3000/api/v1/user/settings" \
              | jq

          # create remote repository in gitea.
          curl \
            -s \
            -u "$GITEA_USERNAME:$GITEA_PASSWORD" \
            -X POST \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{"name": "test"}' \
            http://localhost:3000/api/v1/user/repos \
            | jq

          # execute our application.
          ./bin/Release/net6.0/UseLibgit2sharp

          # list the local repository log.
          git --git-dir tmp/test/.git log --oneline
